---

- name: on hosts
  hosts: localhost
  connection: local
  tasks:
  - name: Unarchive a file that is already on the remote machine
    unarchive:
      src: /home/harshit/Desktop/abhi/apache-tomcat-8.5.38.tar.gz
      dest: /mnt
  - name: Rename a folder
    shell: sudo mv /mnt/apache-tomcat-8.5.38/ /mnt/tomcat
